export const authTypes = {
  SET_TEMP_USER: 'SET_TEMP_USER',
  SET_TEMP_USER_DATA: 'SET_TEMP_USER_DATA',
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',
  CHANGE_USER_REQUEST: 'CHANGE_USER_REQUEST',
  CHANGE_USER_SUCCESS: 'CHANGE_USER_SUCCESS',
  CHANGE_USER_FAILURE: 'CHANGE_USER_FAILURE',
  LOGOUT_USER: 'LOGOUT_USER',
  REGISTER_REQUEST: 'REGISTER_REQUEST',
  REGISTER_SUCCESS: 'REGISTER_SUCCESS',
  REGISTER_FAILURE: 'REGISTER_FAILURE',
};

export const athleteTypes = {
  FETCH_REQUEST: 'FETCH_ATHLETE_REQUEST',
  FETCH_SUCCESS: 'FETCH_ATHLETE_SUCCESS',
  FETCH_FAILURE: 'FETCH_ATHLETE_FAILURE',

  CREATE_REQUEST: 'CREATE_ATHLETE_REQUEST',
  CREATE_SUCCESS: 'CREATE_ATHLETE_SUCCESS',
  CREATE_FAILURE: 'CREATE_ATHLETE_FAILURE',

  REMOVE_REQUEST: 'REMOVE_ATHLETE_REQUEST',
  REMOVE_SUCCESS: 'REMOVE_ATHLETE_SUCCESS',
  REMOVE_FAILURE: 'REMOVE_ATHLETE_FAILURE',

  UPDATE_REQUEST: 'UPDATE_ATHLETE_REQUEST',
  UPDATE_SUCCESS: 'UPDATE_ATHLETE_SUCCESS',
  UPDATE_FAILURE: 'UPDATE_ATHLETE_FAILURE',
};

export const fiadoTypes = {
  CREATE_FIADO_REQUEST: 'CREATE_FIADO_REQUEST',
  CREATE_FIADO_SUCCESS: 'CREATE_FIADO_SUCCESS',
  CREATE_FIADO_FAILURE: 'CREATE_FIADO_FAILURE',

  FETCH_FIADOS_REQUEST: 'FETCH_FIADOS_REQUEST',
  FETCH_FIADOS_SUCCESS: 'FETCH_FIADOS_SUCCESS',
  FETCH_FIADOS_FAILURE: 'FETCH_FIADOS_FAILURE',

  FETCH_PEOPLES_REQUEST: 'FETCH_PEOPLES_REQUEST',
  FETCH_PEOPLES_SUCCESS: 'FETCH_PEOPLES_SUCCESS',
  FETCH_PEOPLES_FAILURE: 'FETCH_PEOPLES_FAILURE',

  REMOVE_FIADO_REQUEST: 'REMOVE_FIADO_REQUEST',
  REMOVE_FIADO_SUCCESS: 'REMOVE_FIADO_SUCCESS',
  REMOVE_FIADO_FAILURE: 'REMOVE_FIADO_FAILURE',

  UPDATE_FIADO_REQUEST: 'UPDATE_FIADO_REQUEST',
  UPDATE_FIADO_SUCCESS: 'UPDATE_FIADO_SUCCESS',
  UPDATE_FIADO_FAILURE: 'UPDATE_FIADO_FAILURE',

  PUSH: 'PUSH_NEW_FIADO',
  RESET: 'RESET_FIADOS',
};

const types = {
  SET_TIMER: 'SET_TIMER',
  SWITCH_TIMER: 'SWITCH_TIMER',

  TOOGLE_THEME: 'TOOGLE_THEME',
  PERSIST_REHYDRATE: 'persist/REHYDRATE',
};

export default types;
