export const authTypes = {
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',

  FETCH_REQUEST: 'FETCH_USERS_REQUEST',
  FETCH_SUCCESS: 'FETCH_USERS_SUCCESS',
  FETCH_FAILURE: 'FETCH_USERS_FAILURE',

  REGISTER_REQUEST: 'REGISTER_REQUEST',
  REGISTER_SUCCESS: 'REGISTER_SUCCESS',
  REGISTER_FAILURE: 'REGISTER_FAILURE',

  REMOVE_REQUEST: 'REMOVE_USER_REQUEST',
  REMOVE_SUCCESS: 'REMOVE_USER_SUCCESS',
  REMOVE_FAILURE: 'REMOVE_USER_FAILURE',

  CHANGE_USER_REQUEST: 'CHANGE_USER_REQUEST',
  CHANGE_USER_SUCCESS: 'CHANGE_USER_SUCCESS',
  CHANGE_USER_FAILURE: 'CHANGE_USER_FAILURE',

  LOGOUT_USER: 'LOGOUT_USER',
};

export const athleteTypes = {
  FETCH_REQUEST: 'FETCH_ATHLETE_REQUEST',
  FETCH_SUCCESS: 'FETCH_ATHLETE_SUCCESS',
  FETCH_FAILURE: 'FETCH_ATHLETE_FAILURE',

  CREATE_REQUEST: 'CREATE_ATHLETE_REQUEST',
  CREATE_SUCCESS: 'CREATE_ATHLETE_SUCCESS',
  CREATE_FAILURE: 'CREATE_ATHLETE_FAILURE',

  REMOVE_REQUEST: 'REMOVE_ATHLETE_REQUEST',
  REMOVE_SUCCESS: 'REMOVE_ATHLETE_SUCCESS',
  REMOVE_FAILURE: 'REMOVE_ATHLETE_FAILURE',

  UPDATE_REQUEST: 'UPDATE_ATHLETE_REQUEST',
  UPDATE_SUCCESS: 'UPDATE_ATHLETE_SUCCESS',
  UPDATE_FAILURE: 'UPDATE_ATHLETE_FAILURE',
};

export const categoryTypes = {
  FETCH_REQUEST: 'FETCH_CATEGORY_REQUEST',
  FETCH_SUCCESS: 'FETCH_CATEGORY_SUCCESS',
  FETCH_FAILURE: 'FETCH_CATEGORY_FAILURE',

  CREATE_REQUEST: 'CREATE_CATEGORY_REQUEST',
  CREATE_SUCCESS: 'CREATE_CATEGORY_SUCCESS',
  CREATE_FAILURE: 'CREATE_CATEGORY_FAILURE',

  REMOVE_REQUEST: 'REMOVE_CATEGORY_REQUEST',
  REMOVE_SUCCESS: 'REMOVE_CATEGORY_SUCCESS',
  REMOVE_FAILURE: 'REMOVE_CATEGORY_FAILURE',

  UPDATE_REQUEST: 'UPDATE_CATEGORY_REQUEST',
  UPDATE_SUCCESS: 'UPDATE_CATEGORY_SUCCESS',
  UPDATE_FAILURE: 'UPDATE_CATEGORY_FAILURE',
};

export const actionLogTypes = {
  FETCH: 'FETCH_ACTIONLOGS_REQUEST',
  FETCH_SUCCESS: 'FETCH_ACTIONLOGS_SUCCESS',
  FETCH_FAILURE: 'FETCH_ACTIONLOGS_FAILURE',
};

const types = {
  TOOGLE_THEME: 'TOOGLE_THEME',
  PERSIST_REHYDRATE: 'persist/REHYDRATE',
};

export default types;
